### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by GewelsJI** [lartpang/HDFNet#2]
请问一下你提供的结果图压缩包里面里面：

HDFNet_Res50 和 HDFNet_Res50_STEREO有什么区别

**Comment by lartpang** [comment]
@GewelsJI 在参考链接里提供了两个版本的STEREO，一个797，一个1000。

我在`_STEREO`中提供了这两个版本的结果。在没有该后缀的结果里仅提供了1000版本的结果。

> 数据集参考：https://github.com/jiwei0921/RGBD-SOD-datasets#rgb-d-saliency-datasets

**Comment by GewelsJI** [comment]
好的，谢谢作者！

MY_ <notifications@github.com> 于2020年8月13日周四 下午4:01写道：
