### ISSUE TITLE
关于FPS的问题

### ISSUE THREAD

**Issue by Zakeiswo** [lartpang/HDFNet#4]
您好，谢谢您的工作。请问一下您论文里描述的FPS是70.28FPS，但是我用您的工具在2080ti上测VGG16只能测到50左右，请问有什么原因吗。
-----------------------------------------------------------
` ==>> 在GPU上测试模型 <<== 
不加载权重
开始统计.../home/zakeyao/DATASET_ori/SOD/RGBD/TesetSet/DUT-RGBD/test_data
HDFNet_VGG16:te=>400: 100%|█████████▉| 399/400 [00:11<00:00, 34.47it/s]
 ==>> Model: HDFNet_VGG16: Dataset: dut-rgbd1 
 ==>> FPS: 46.13068688057626
 ==>> 在GPU上测试模型 <<== 
HDFNet_VGG16:te=>1:   0%|          | 0/400 [00:00<?, ?it/s]不加载权重
开始统计.../home/zakeyao/DATASET_ori/SOD/RGBD/TesetSet/DUT-RGBD/test_data
                                                                       
 ==>> Model: HDFNet_VGG16: Dataset: dut-rgbd2 
 ==>> FPS: 52.355917290886254
 ==>> 在GPU上测试模型 <<== 
HDFNet_VGG16:te=>1:   0%|          | 0/400 [00:00<?, ?it/s]不加载权重
开始统计.../home/zakeyao/DATASET_ori/SOD/RGBD/TesetSet/DUT-RGBD/test_data
                                                                       
 ==>> Model: HDFNet_VGG16: Dataset: dut-rgbd3 
 ==>> FPS: 51.94418831833993
 ==>> 在GPU上测试模型 <<== 
不加载权重
开始统计.../home/zakeyao/DATASET_ori/SOD/RGBD/TesetSet/DUT-RGBD/test_data
HDFNet_VGG16:te=>400:  99%|█████████▉| 395/400 [00:10<00:00, 38.02it/s]
 ==>> Model: HDFNet_VGG16: Dataset: dut-rgbd4 
 ==>> FPS: 52.353228115215686
 ==>> 所有模型速度测试完毕 <<== `

**Comment by lartpang** [comment]
@Zakeiswo 论文中确实存在一些速度测试的错误。这主要是因为我之前没有注意到pytorch测试模型前向传播速度的一个需要注意的地方。更细致的讨论可以看：https://github.com/lartpang/MINet/issues/5

我已经把使用这个方法测试的结果更新在了论文的arixv版本里：https://arxiv.org/abs/2007.06227

感谢指出这一点。

**Comment by Zakeiswo** [comment]
Thx
